project:
  type: website
  resources: 
    - images/*

website:
  title: "Nexus: Crowdsourced ML Resources"
  page-navigation: true
  
  sidebar:
    tools:
      - icon: github
        href: https://github.com/UW-Madison-DataScience/ML-X-Community
        text: "GitHub organization"
    background: "#dbd9d9"
    logo: "images/ML+X_Logo_Secondary_Transparent.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - auto: Guides
      - text: "Local workshops"
        href: Workshops/index.qmd
      - auto: EDA-examples
      - href: pretrained-models.qmd
        text: "Pretrained models"
      - href: external-guides.qmd
        text: "External guides"
      - href: ML-stories/index.qmd
        text: "ML stories"
      - href: glossary.qmd
        text: "Glossary of ML terms"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    # css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

